### ISSUE TITLE
AttributeError: function 'InetNtopW' not found

### ISSUE THREAD

**Issue by CNMan** [hickeroar/win_inet_pton#8]
after upgrade to 1.1.0

```python
>pip install -r requirements.txt --upgrade
Traceback (most recent call last):
  File "e:\vmware\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "e:\vmware\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\VMware\Python27\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "e:\vmware\python27\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "e:\vmware\python27\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "e:\vmware\python27\lib\site-packages\pip\_internal\cli\main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "e:\vmware\python27\lib\site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "e:\vmware\python27\lib\site-packages\pip\_internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "e:\vmware\python27\lib\site-packages\pip\_internal\cli\base_command.py", line 19, in <module>
    from pip._internal.download import PipSession
  File "e:\vmware\python27\lib\site-packages\pip\_internal\download.py", line 15, in <module>
    from pip._vendor import requests, six, urllib3
  File "e:\vmware\python27\lib\site-packages\pip\_vendor\requests\__init__.py", line 117, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "e:\vmware\python27\lib\site-packages\pip\_vendor\requests\api.py", line 13, in <module>
    from . import sessions
  File "e:\vmware\python27\lib\site-packages\pip\_vendor\requests\sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "e:\vmware\python27\lib\site-packages\pip\_vendor\requests\adapters.py", line 44, in <module>
    from pip._vendor.urllib3.contrib.socks import SOCKSProxyManager
  File "e:\vmware\python27\lib\site-packages\pip\_vendor\urllib3\contrib\socks.py", line 27, in <module>
    import socks
  File "e:\vmware\python27\lib\site-packages\socks.py", line 74, in <module>
    import win_inet_pton
  File "e:\vmware\python27\lib\site-packages\win_inet_pton.py", line 126, in <module>
    inject_into_socket()
  File "e:\vmware\python27\lib\site-packages\win_inet_pton.py", line 27, in inject_into_socket
    InetNtopW = ctypes.windll.ws2_32.InetNtopW
  File "e:\vmware\python27\lib\ctypes\__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "e:\vmware\python27\lib\ctypes\__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'InetNtopW' not found
```

**Comment by sethmlarson** [comment]
Hm, maybe we'll have to use both InetNtopW and fallback on WSAAddressToStringA which is strange because WSAAddressToStringA was added to Windows at the same time as InetNtopW per the docs? What Windows version are you using?

**Comment by CNMan** [comment]
Windows Server 2003 R2 with SP2

**Comment by sethmlarson** [comment]
I can add it back as a fallback, let me just test it.

**Comment by lyellread** [comment]
I happen to also be using this and it would be helpful to have `InetNtopW` back! Thank you!

**Comment by 892768447** [comment]
here is my fix

[win_inet_pton_patch.zip](https://github.com/hickeroar/win_inet_pton/files/5275206/win_inet_pton_patch.zip)

or maybe like this: https://github.com/hickeroar/win_inet_pton/pull/5/commits/9986ca23f3b3a48fa909e050046dee83b1351e6e

**Comment by sethmlarson** [comment]
I'd accept a PR adding support for the fallback.

**Comment by 892768447** [comment]
> I'd accept a PR adding support for the fallback.

I'll write a fix later and add tests and submit pr

**Comment by Jury123** [comment]
I have exactly the same error! But dear Herr 892768447 created "win_inet_pton_patch" dll only for x32. I have Win XP x64 SP2 (AKA - Server 2003 x64). Accordingly, my Python 2.7.18 and Git 2.10.0 are 64-bit. The patch doesn't work. If you install the appropriate 32-bit version, performance is restored. But the system message "function 'InetNtopW' not found" remains.
  Please create an x64 version of the dll for the patch.
  In my opinion, it is best to implement the 'InetNtopW' function in the program itself, this is only a dozen lines of code!

**Comment by 892768447** [comment]
> I have exactly the same error! But dear Herr 892768447 created "win_inet_pton_patch" dll only for x32. I have Win XP x64 SP2 (AKA - Server 2003 x64). Accordingly, my Python 2.7.18 and Git 2.10.0 are 64-bit. The patch doesn't work. If you install the appropriate 32-bit version, performance is restored. But the system message "function 'InetNtopW' not found" remains.
> Please create an x64 version of the dll for the patch.
> In my opinion, it is best to implement the 'InetNtopW' function in the program itself, this is only a dozen lines of code!

see https://github.com/hickeroar/win_inet_pton/commit/9986ca23f3b3a48fa909e050046dee83b1351e6e

here is fix code,but some test can not pass

```python
# This software released into the public domain. Anyone is free to copy,
# modify, publish, use, compile, sell, or distribute this software,
# either in source code form or as a compiled binary, for any purpose,
# commercial or non-commercial, and by any means.

import socket
import os
import sys
import ctypes


def inject_into_socket():

    class in_addr(ctypes.Structure):
        _fields_ = [("S_addr", ctypes.c_ubyte * 4)]

    class in6_addr(ctypes.Structure):
        _fields_ = [("Byte", ctypes.c_ubyte * 16)]

    if hasattr(ctypes, "windll"):
        # InetNtopW(
        #   INT         family,
        #   const VOID  *pAddr,
        #   PWSTR       pStringBuf,
        #   size_t      StringBufSize
        # ) -> PCWSTR
        InetNtopW = ctypes.windll.ws2_32.InetNtopW

        # InetPtonW(
        #   INT         family,
        #   PCWSTR      pszAddrString,
        #   PVOID       pAddrBuf
        # ) -> INT
        InetPtonW = ctypes.windll.ws2_32.InetPtonW

        # WSAGetLastError() -> INT
        WSAGetLastError = ctypes.windll.ws2_32.WSAGetLastError
    else:

        def not_windows():
            raise SystemError("Invalid platform. ctypes.windll must be available.")

        InetNtopW = not_windows
        InetPtonW = not_windows
        WSAGetLastError = not_windows

    def inet_pton(address_family, ip_string):
        if sys.version_info[0] > 2 and isinstance(ip_string, bytes):
            raise TypeError("inet_pton() argument 2 must be str, not bytes")

        if address_family == socket.AF_INET:
            family = 2
            addr = in_addr()
        elif address_family == socket.AF_INET6:
            family = 23
            addr = in6_addr()
        else:
            raise OSError("unknown address family")

        ip_string = ctypes.c_wchar_p(ip_string)
        ret = InetPtonW(ctypes.c_int(family), ip_string, ctypes.byref(addr))

        if ret == 1:
            if address_family == socket.AF_INET:
                return ctypes.string_at(addr.S_addr, 4)
            else:
                return ctypes.string_at(addr.Byte, 16)
        elif ret == 0:
            raise socket.error("illegal IP address string passed to inet_pton")
        else:
            err = WSAGetLastError()
            if err == 10047:
                e = socket.error("unknown address family")
            elif err == 10014:
                e = OSError("bad address")
            else:
                e = OSError("unknown error from inet_ntop")
            e.errno = err
            raise e

    def inet_ntop(address_family, packed_ip):
        if address_family == socket.AF_INET:
            addr = in_addr()
            if len(packed_ip) != ctypes.sizeof(addr.S_addr):
                raise ValueError("packed IP wrong length for inet_ntop")

            ctypes.memmove(addr.S_addr, packed_ip, 4)
            buffer_len = 16
            family = 2

        elif address_family == socket.AF_INET6:
            addr = in6_addr()
            if len(packed_ip) != ctypes.sizeof(addr.Byte):
                raise ValueError("packed IP wrong length for inet_ntop")

            ctypes.memmove(addr.Byte, packed_ip, 16)
            buffer_len = 57
            family = 23
        else:
            raise ValueError("unknown address family")

        buffer = ctypes.create_unicode_buffer(buffer_len)

        ret = InetNtopW(
            ctypes.c_int(family),
            ctypes.byref(addr),
            ctypes.byref(buffer),
            ctypes.sizeof(buffer),
        )
        if ret is None:
            err = WSAGetLastError()
            if err == 10047:
                e = ValueError("unknown address family")
            else:
                e = OSError("unknown error from inet_ntop")
            e.errno = err

        return ctypes.wstring_at(buffer, buffer_len).rstrip("\x00")

    # Adding our two functions to the socket library
    socket.inet_pton = inet_pton
    socket.inet_ntop = inet_ntop


def inject_into_xp_socket():
    # For Windows Xp

    class SockAddr(ctypes.Structure):
        _fields_ = [("sa_family", ctypes.c_short),
                    ("__pad1", ctypes.c_ushort),
                    ("ipv4_addr", ctypes.c_byte * 4),
                    ("ipv6_addr", ctypes.c_byte * 16),
                    ("__pad2", ctypes.c_ulong)]

    if hasattr(ctypes, 'windll'):
        WSAStringToAddressA = ctypes.windll.ws2_32.WSAStringToAddressA
        WSAAddressToStringA = ctypes.windll.ws2_32.WSAAddressToStringA
    else:
        def not_windows():
            raise SystemError(
                "Invalid platform. ctypes.windll must be available."
            )

        WSAStringToAddressA = not_windows
        WSAAddressToStringA = not_windows

    def inet_pton(address_family, ip_string):
        addr = SockAddr()
        addr.sa_family = address_family
        addr_size = ctypes.c_int(ctypes.sizeof(addr))

        if WSAStringToAddressA(
                ip_string,
                address_family,
                None,
                ctypes.byref(addr),
                ctypes.byref(addr_size)
        ) != 0:
            raise socket.error(ctypes.FormatError())

        if address_family == socket.AF_INET:
            return ctypes.string_at(addr.ipv4_addr, 4)
        if address_family == socket.AF_INET6:
            return ctypes.string_at(addr.ipv6_addr, 16)

        raise socket.error('unknown address family')

    def inet_ntop(address_family, packed_ip):
        addr = SockAddr()
        addr.sa_family = address_family
        addr_size = ctypes.c_int(ctypes.sizeof(addr))

        if address_family == socket.AF_INET:
            if len(packed_ip) != ctypes.sizeof(addr.ipv4_addr):
                raise socket.error('packed IP wrong length for inet_ntoa')
            ctypes.memmove(addr.ipv4_addr, packed_ip, 4)
            #  15: IPv4 address
            #   1: Terminating null byte
            buffer_len = 16
        elif address_family == socket.AF_INET6:
            if len(packed_ip) != ctypes.sizeof(addr.ipv6_addr):
                raise socket.error('packed IP wrong length for inet_ntoa')
            ctypes.memmove(addr.ipv6_addr, packed_ip, 16)
            #  45: IPv6 address including embedded IPv4 address
            #  11: Scope Id
            #   1: Terminating null byte
            buffer_len = 57
        else:
            raise socket.error('unknown address family')

        ip_string = ctypes.create_string_buffer(buffer_len)
        ip_string_size = ctypes.c_int(ctypes.sizeof(ip_string))

        if WSAAddressToStringA(
                ctypes.byref(addr),
                addr_size,
                None,
                ip_string,
                ctypes.byref(ip_string_size)
        ) != 0:
            raise socket.error(ctypes.FormatError())

        return ip_string[:ip_string_size.value - 1]

    # Adding our two functions to the socket library
    socket.inet_pton = inet_pton
    socket.inet_ntop = inet_ntop


if os.name == "nt" and not hasattr(socket, "inet_pton"):
    if not hasattr(ctypes.windll.ws2_32, "InetNtopW") or not hasattr(ctypes.windll.ws2_32, "InetPtonW"):
        inject_into_socket = inject_into_xp_socket
    inject_into_socket()

```
